#include <linux/input.h>
#include <stdio.h>
#include <linux/uinput.h>
#include <linux/ioctl.h>
#include <fcntl.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <stdlib.h>
